name:                MT-2lab-recursive-parsing
version:             0.1.0.0
github:              "Geny200/MT-2lab-recursive-parsing"
license:             LGPL-3
author:              "Geny200"
maintainer:          "-"
copyright:           "2020 Geny200"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/Geny200/MT-2lab-recursive-parsing#readme>

dependencies:
- base >= 4.7 && < 5
- transformers >= 0.2   && < 0.6
- free >= 5 && < 6
- mtl >= 2.2.2
- process >= 1.6.7
- regex-tdfa
- lens
- split
- containers

library:
  source-dirs: src

executables:
  MT-2lab-recursive-parsing-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - MT-2lab-recursive-parsing

tests:
  MT-2lab-recursive-parsing-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - MT-2lab-recursive-parsing
    - HUnit
    - QuickCheck
    - hspec
